### ISSUE TITLE
staticmap.openstreetmap.de returns black images

### ISSUE THREAD

**Issue by stephankn** [fossgis/openstreetmap.de#36]
besides the demo image, other lat/lon combinations return black images (with logo).
Something broken with fetching tiles?

Demo page which returns black images:
https://harrywood.co.uk/maps/examples/static-image/staticmaplite.html

Would be nice if service could be repaired. wiki.openstreetmap.org needs a service to fetch static maps.

**Comment by joto** [comment]
Nicht unsere Baustelle. Hier gehts um openstreetmap.de. Und auch wahrscheinlich total veraltet.

**Comment by stephankn** [comment]
GET https://staticmap.openstreetmap.de/staticmap.php?center=51.522318,-0.083446&zoom=12&size=240x200&markers=51.522318,-0.083446,red-pushpin

still returns black image. 

services on openstreetmap.de are to my knowledge still run by fossgis, no?

I have no idea about how it was meanwhile solved in the wiki. I think functionality was completely removed from wiki and no more static maps are displayed. I am fine to have this issue closed. Maybe you want to completely remove the defunct staticmap site. If it is broken now since more than three years and unmaintained, it might have other unpatched vulnerable services as well.

**Comment by joto** [comment]
Ah, sorry, didn't understand how this relates to openstreetmap.de. It definitely doesn't have anything to do with this repository, because staticmap.openstreetmap.de is somewhere else. I have to find out where. There are several services run (or not run as it seems) by individuals under the openstreetmap.de Domain not related to the main web site.
